.TH "Acceuil.cpp" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Acceuil.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Acceuil\&.h'\fP
.br
\fC#include 'Horloge\&.h'\fP
.br
\fC#include 'ChampDeJeu\&.h'\fP
.br
\fC#include 'Case\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QMenuBar>\fP
.br
\fC#include <qmessagebox\&.h>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QFrame>\fP
.br
\fC#include <QInputDialog>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QStatusBar>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QScopedArrayPointer>\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Demineur à partir du code source\&.
