.TH "Case.h" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Case.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Position\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QStateMachine>\fP
.br
\fC#include <QState>\fP
.br
\fC#include <QFinalState>\fP
.br
\fC#include <QSignalMapper>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCase\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCASE_H\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define CASE_H"

.PP
Définition à la ligne 4 du fichier Case\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Demineur à partir du code source\&.
