.TH "CompteurDeMine" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompteurDeMine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CompteurDeMine\&.h>\fP
.PP
Est dérivée de QLCDNumber\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCompteurDeMine\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBSetNombreMines\fP (int numMines)"
.br
.ti -1c
.RI "void \fBSetNombreDrapeau\fP (unsigned int flagCount)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const override"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 6 du fichier CompteurDeMine\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CompteurDeMine::CompteurDeMine (QWidget * parent = \fCnullptr\fP)"

.PP
Définition à la ligne 4 du fichier CompteurDeMine\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CompteurDeMine::SetNombreDrapeau (unsigned int flagCount)"

.PP
Définition à la ligne 21 du fichier CompteurDeMine\&.cpp\&.
.SS "void CompteurDeMine::SetNombreMines (int numMines)"

.PP
Définition à la ligne 15 du fichier CompteurDeMine\&.cpp\&.
.SS "QSize CompteurDeMine::sizeHint () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 27 du fichier CompteurDeMine\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Demineur à partir du code source\&.
