.TH "EtatJeu.h" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatJeu.h
.SH SYNOPSIS
.br
.PP
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBEtatJeu\fP { \fBAttente\fP, \fBEchec\fP, \fBEncours\fP, \fBSucces\fP }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBEtatJeu\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIAttente \fP\fP
.TP
\fB\fIEchec \fP\fP
.TP
\fB\fIEncours \fP\fP
.TP
\fB\fISucces \fP\fP
.PP
Définition à la ligne 4 du fichier EtatJeu\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Demineur à partir du code source\&.
