.TH "Horloge" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Horloge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Horloge\&.h>\fP
.PP
Est dérivée de QLCDNumber\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBHorloge\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBincrementTime\fP ()"
.br
.ti -1c
.RI "int \fBtime\fP () const"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const override"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 5 du fichier Horloge\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Horloge::Horloge (QWidget * parent = \fCnullptr\fP)"

.PP
Définition à la ligne 3 du fichier Horloge\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Horloge::incrementTime ()"

.PP
Définition à la ligne 14 du fichier Horloge\&.cpp\&.
.SS "QSize Horloge::sizeHint () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 24 du fichier Horloge\&.cpp\&.
.SS "int Horloge::time () const"

.PP
Définition à la ligne 19 du fichier Horloge\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Demineur à partir du code source\&.
