.TH "main.cpp" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Acceuil\&.h'\fP
.br
\fC#include <QApplication>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Définition à la ligne 5 du fichier main\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Demineur à partir du code source\&.
