.TH "md__r_e_a_d_m_e" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Demineur 
\&.\&.* Le projet a été réalisé au cours de notre cours de programmation orienté Objet en C++ dans le cadre du Master CIC/UTBM\&.
.SS "Technologies Utilisées:"
.IP "\(bu" 2
C++
.IP "\(bu" 2
Qt
.PP
.SS "Capttures d'écrans"
.SH "<img src='https://raw\&.githubusercontent\&.com/daniwxcode/Demineur/master/Captures/ChoixNiveau\&.png' alt='Alt'/>"
.PP
.SH "<img src='https://raw\&.githubusercontent\&.com/daniwxcode/Demineur/master/Captures/intermediaire\&.png' alt='Alt'/>"
.PP
.PP
.PP
 
.SH "<img src='https://raw\&.githubusercontent\&.com/daniwxcode/Demineur/master/Captures/victoire\&.png' alt='Alt'/>"
.PP
.SH "<img src='https://raw\&.githubusercontent\&.com/daniwxcode/Demineur/master/Captures/succes\&.png' alt='Alt'/>"
.PP
.SH "<img src='https://raw\&.githubusercontent\&.com/daniwxcode/Demineur/master/Captures/jeux\&.PNG' alt='Alt'/>"
.PP
.SH "<img src='https://raw\&.githubusercontent\&.com/daniwxcode/Demineur/master/Captures/DefaiteMessage\&.png' alt='Alt'/>"
.PP
.SH "<img src='https://raw\&.githubusercontent\&.com/daniwxcode/Demineur/master/Captures/Defaite\&.jpg' alt='Alt'/>"
.PP

