.TH "Niveau.h" 3 "Dimanche 16 Août 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Niveau.h
.SH SYNOPSIS
.br
.PP
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBNiveau\fP { \fBFacile\fP, \fBIntermediaire\fP, \fBExpert\fP }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBNiveau\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIFacile \fP\fP
.TP
\fB\fIIntermediaire \fP\fP
.TP
\fB\fIExpert \fP\fP
.PP
Définition à la ligne 3 du fichier Niveau\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Demineur à partir du code source\&.
